language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev --prefer-source;

script: phpunit --configuration module/Download/test/phpunit.xml --coverage-clover=coverage.clover
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
